services:
  actual-budget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-budget-container
    restart: unless-stopped
    ports:
      - 5006:5006
    networks:
      - actual-budget-network
    environment:
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=5006
    volumes:
      - ./actual-data:/data
networks:
  actual-budget-network:
