services:
  actual:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - 5006:5006
    environment:
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=5006
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    restart: unless-stopped
